
networks:
  conversor-net:
    driver: bridge

volumes:
  rabbitmq_data:
  minio_data:
  jobs_data:

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - conversor-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    networks:
      - conversor-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - conversor-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_ingestao
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MINIO_HOST=minio:9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - jobs_data:/app/data
    networks:
      - conversor-net
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MINIO_HOST=minio:9000
      - MINIO_PUBLIC_HOST=localhost:9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
    volumes:
      - jobs_data:/app/data
    networks:
      - conversor-net
    deploy:
      replicas: 4
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - conversor-net
    depends_on:
      - api